repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
      args: [ --fix, --unsafe-fixes ]
    - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
    -   id: prettier
        types_or: [css, javascript, html]
        additional_dependencies:
        - prettier@3.4.2
        - eslint-config-prettier
        - '@prettier/plugin-xml@0.12.0'
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.18.0'
    hooks:
    -   id: eslint
