repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
      args: [ --fix, --unsafe-fixes ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: 'v9.18.0'
  hooks:
  -   id: eslint
      args: ["--fix"]
- repo: https://github.com/rtts/djhtml
  rev: '3.0.7'
  hooks:
    - id: djhtml
    - id: djcss
    - id: djjs