services:
  anyblok:
    image: ghcr.io/petrus-v/band-management:latest
    build:
      context: ./
    networks:
      - internal
    volumes:
      - bm_data:/data/bm
      - ./app.ci.docker.cfg:/etc/app.cfg
    command: ["anyblok_uvicorn", "-c", "/etc/app.cfg", "--host", "0.0.0.0"]
    ports:
      - 8000:8000
    environment:
      DATA_PATH: "/data/bm"
      JWT_SECRET_KEY: CHANGE_ME

  db:
    image: postgres:18.0
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-emptydb}
      POSTGRES_USER: ${POSTGRES_USER:-bmuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bmpwd}
    networks:
      - internal
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER:-bmuser} -d ${POSTGRES_DB:-emptydb}'",
        ]
      interval: 3s
      timeout: 2s
      retries: 3

networks:
  internal:

volumes:
  pg_data:
    driver: local
  bm_data:
    driver: local
